name: globalposition
description: Global position feature - home screen
publish_to: 'none'

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  bloc_concurrency:
  common:
    path: ../../core/common
  dio:
  domain:
    path: ../../core/domain
  flutter:
    sdk: flutter
  flutter_bloc:
  fpdart:
  freezed_annotation:
  promotions:
    path: ../../libs/promotions
  ui:
    path: ../../core/ui

dev_dependencies:
  bloc_test:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  mocktail:
  very_good_analysis:
