targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.freezed.dart'
