name: accounts
description: Accounts feature
publish_to: 'none'

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  common:
    path: ../../core/common
  cookie_jar:
  dio:
  easy_localization:
  domain:
    path: ../../core/domain
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_riverpod:
  fpdart:
  freezed_annotation:
  go_router:
  json_annotation:
  retrofit:
  security:
    path: ../../core/security
  ui:
    path: ../../core/ui
  webview_lib:
    path: ../../libs/webview

dev_dependencies:
  bloc_test:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  mocktail:
  retrofit_generator:
  very_good_analysis:
