name: common
description: Shared utilities, networking, config, error handling
publish_to: 'none'

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  crypto:
  dio:
  dio_cache_interceptor:
  easy_localization:
  flutter:
    sdk: flutter
  flutter_riverpod:
  fpdart:
  freezed_annotation:
  go_router:

flutter:
  assets:
    - assets/translations/

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  very_good_analysis:
