import 'dart:developer' as developer;
import 'dart:io';

import 'package:app_device_integrity/app_device_integrity.dart';

/// Contract for generating platform attestation tokens.
///
/// - **Android**: Uses [Play Integrity API](https://developer.android.com/google/play/integrity/overview)
/// - **iOS**: Uses [App Attest / DeviceCheck](https://developer.apple.com/documentation/devicecheck/establishing-your-app-s-integrity)
///
/// The generated token must be sent to the bank's backend in a request header
/// (e.g. `X-Integrity-Token`). The backend validates the token directly
/// against Google/Apple servers — no third-party services involved.
abstract class IntegrityAttestationService {
  /// Requests an attestation token from the platform provider.
  ///
  /// [challengeUuid] is a one-time challenge generated by the backend
  /// to prevent replay attacks.
  ///
  /// Returns the signed token string, or `null` if attestation is
  /// unavailable (e.g. emulator, unsupported device).
  Future<String?> getAttestationToken({required String challengeUuid});
}

/// Production implementation using `app_device_integrity` which wraps
/// Play Integrity (Android) and App Attest (iOS).
class IntegrityAttestationServiceImpl implements IntegrityAttestationService {
  IntegrityAttestationServiceImpl({
    required int gcpProjectId,
  }) : _gcpProjectId = gcpProjectId;

  /// Google Cloud Platform project ID (Android only).
  /// On iOS this value is ignored.
  final int _gcpProjectId;

  static const _tag = 'IntegrityAttestation';

  @override
  Future<String?> getAttestationToken({required String challengeUuid}) async {
    try {
      final plugin = AppDeviceIntegrity();

      final String? token;
      if (Platform.isAndroid) {
        token = await plugin.getAttestationServiceSupport(
          challengeString: challengeUuid,
          gcp: _gcpProjectId,
        );
      } else {
        token = await plugin.getAttestationServiceSupport(
          challengeString: challengeUuid,
        );
      }

      developer.log('Attestation token obtained', name: _tag);
      return token;
    } on Exception catch (e) {
      developer.log('Attestation failed: $e', name: _tag);
      return null;
    }
  }
}

/// Mock implementation for development that returns a fake token.
class MockIntegrityAttestationService implements IntegrityAttestationService {
  @override
  Future<String?> getAttestationToken({required String challengeUuid}) async {
    return 'mock-integrity-token-$challengeUuid';
  }
}
